--storesテーブル
CREATE TABLE IF NOT EXISTS stores (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,  
image_name VARCHAR(255),
description VARCHAR(255) NOT NULL,
opening_hours VARCHAR(50) NULL,
closing_time TIME NOT NULL,
postal_code VARCHAR(50) NOT NULL,
address VARCHAR(255) NOT NULL,
phone_number VARCHAR(50) NOT NULL,
closed_day DATE NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


--categoryテーブル
CREATE TABLE IF NOT EXISTS category (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

ALTER TABLE stores ADD CONSTRAINT fk_category FOREIGN KEY (category) REFERENCES category(id);

